### ISSUE TITLE
Version 1.2.10 - ClassCastException in specific devices (Lenovo, Asus)

### ISSUE THREAD

**Issue by beqirajd** [akexorcist/Localization#122]
After upgrading to`1.2.10` some crashes were reported in:

1. Lenovo Tab M10 FHD Plus
2. Lenovo Tab E10
3. ZenFone 6 (ZS630KL) (WW) / 6Z (ZS630KL) (IN)

with Android Versions 8, 10 and 11.

When my activity class that extends `LocalizationActivity` is created, this crash occurs:

```
Caused by java.lang.ClassCastException: be.a cannot be cast to androidx.fragment.app.Fragment
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
       at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
       at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
       at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
       at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
       at com.akexorcist.localizationactivity.ui.LocalizationActivity.onCreate(LocalizationActivity.java:24)
       at com.xxx.MyCustomActivity.onCreate(MyCustomActivity.java:104)
```

**Comment by akexorcist** [comment]
Do you know what `be.a` is ? It was obfuscated.

**Comment by beqirajd** [comment]
> Do you know what `be.a` is ? It was obfuscated.

It is obfuscated class. But I only get the error in production app and unfortunately I cannot figure out what the obfuscated fragment is.

**Comment by akexorcist** [comment]
You can upload `mapping.txt` that generated from obfuscate processing in Google Play.

It will help you to retrace mapping the obfuscated class in production to original class name.

![image](https://user-images.githubusercontent.com/1949576/147132215-ff39f9ed-b1e3-451e-aa40-fed81d5f0062.png)

**Comment by akexorcist** [comment]
Since AndroidX AppCompat has per-app language preferences for backward compatibility. Please migrate this library to AndroidX for more stability, compatibility, and longer support from Google team.

See [Migrate to AndroidX guide](https://github.com/akexorcist/Localization/blob/master/MIGRATE_TO_ANDROIDX.md)

Thank you for your support
