### ISSUE TITLE
Version 1.2.10 => Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: cf

### ISSUE THREAD

**Issue by AxitaKathiriya** [akexorcist/Localization#130]
I'm using the 1.2.10 version of Localization Library.  Please check below logs of crashlytics for more details.

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.tutorialdemo/com.activity.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: cf
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3175)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3312)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:226)
       at android.app.ActivityThread.main(ActivityThread.java:7178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: cf
       at android.os.Parcel.readParcelableCreator(Parcel.java:2855)
       at android.os.Parcel.readParcelable(Parcel.java:2781)
       at android.os.Parcel.readValue(Parcel.java:2684)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
       at android.os.BaseBundle.unparcel(BaseBundle.java:232)
       at android.os.Bundle.getParcelable(Bundle.java:940)
       at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:148)
       at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
       at com.akexorcist.localizationactivity.ui.LocalizationActivity.onCreate(LocalizationActivity.kt:24)
       at com.activity.MainActivity.onCreate(MainActivity.java:192)
       at android.app.Activity.performCreate(Activity.java:7383)
       at android.app.Activity.performCreate(Activity.java:7374)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3155)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3312)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:226)
       at android.app.ActivityThread.main(ActivityThread.java:7178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by FitApps7** [comment]
this issue has been resolved or not in ver 1.2.11?

**Comment by axitasavani** [comment]
Hi, I have also faced this issue as below

```
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: ke
       at android.os.Parcel.readParcelableCreator(Parcel.java:2855)
       at android.os.Parcel.readParcelable(Parcel.java:2781)
       at android.os.Parcel.readValue(Parcel.java:2684)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
       at android.os.BaseBundle.unparcel(BaseBundle.java:232)
       at android.os.Bundle.getParcelable(Bundle.java:940)
       at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:148)
       at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
       at com.akexorcist.localizationactivity.ui.LocalizationActivity.onCreate(LocalizationActivity.kt:24)
       at android.app.Activity.performCreate(Activity.java:7376)
       at android.app.Activity.performCreate(Activity.java:7367)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3155)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3312)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:226)
       at android.app.ActivityThread.main(ActivityThread.java:7178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

**Comment by Jaydipnathani** [comment]
Hi, I have also faced this same issue.
![image_2022_02_16T09_51_51_881Z](https://user-images.githubusercontent.com/54942991/154239566-4e3159eb-2462-47ca-9aec-dd617fceb610.png)

**Comment by FitApps7** [comment]
> Hi, I have also faced this same issue. ![image_2022_02_16T09_51_51_881Z](https://user-images.githubusercontent.com/54942991/154239566-4e3159eb-2462-47ca-9aec-dd617fceb610.png)

in which version?

**Comment by FitApps7** [comment]
> Hi, I have also faced this issue as below
> 
> ```
> Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: ke
>        at android.os.Parcel.readParcelableCreator(Parcel.java:2855)
>        at android.os.Parcel.readParcelable(Parcel.java:2781)
>        at android.os.Parcel.readValue(Parcel.java:2684)
>        at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
>        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
>        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
>        at android.os.Bundle.getParcelable(Bundle.java:940)
>        at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:148)
>        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
>        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
>        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
>        at com.akexorcist.localizationactivity.ui.LocalizationActivity.onCreate(LocalizationActivity.kt:24)
>        at android.app.Activity.performCreate(Activity.java:7376)
>        at android.app.Activity.performCreate(Activity.java:7367)
>        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3155)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3312)
>        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
>        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
>        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loop(Looper.java:226)
>        at android.app.ActivityThread.main(ActivityThread.java:7178)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
> ```

in which version?

**Comment by FitApps7** [comment]
To me in 1.2.11 version this exceptions has been resolved.

**Comment by Jaydipnathani** [comment]
> To me in 1.2.11 version this exceptions has been resolved.

implementation 'com.akexorcist:localization:1.2.10'

**Comment by axitasavani** [comment]
@FitApps7 
 implementation 'com.akexorcist:localization:1.2.10'

in this verion I have faced this issue.
we can't used 1.2.11 

> > Hi, I have also faced this issue as below
> > ```
> > Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: ke
> >        at android.os.Parcel.readParcelableCreator(Parcel.java:2855)
> >        at android.os.Parcel.readParcelable(Parcel.java:2781)
> >        at android.os.Parcel.readValue(Parcel.java:2684)
> >        at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
> >        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
> >        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
> >        at android.os.Bundle.getParcelable(Bundle.java:940)
> >        at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:148)
> >        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
> >        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
> >        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
> >        at com.akexorcist.localizationactivity.ui.LocalizationActivity.onCreate(LocalizationActivity.kt:24)
> >        at android.app.Activity.performCreate(Activity.java:7376)
> >        at android.app.Activity.performCreate(Activity.java:7367)
> >        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
> >        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3155)
> >        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3312)
> >        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> >        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
> >        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
> >        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
> >        at android.os.Handler.dispatchMessage(Handler.java:106)
> >        at android.os.Looper.loop(Looper.java:226)
> >        at android.app.ActivityThread.main(ActivityThread.java:7178)
> >        at java.lang.reflect.Method.invoke(Method.java)
> >        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
> >        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
> > ```
> 
> in which version?

I have faced this issue in " implementation 'com.akexorcist:localization:1.2.10' in this version,
I m not using 1.2.11 bcz it supports 

```
Compile SDK Version 31
Target SDK Version 31
Kotlin : 1.6.10
Gradle : 7.0.2
Gradle Plugin : 4.2.2
Activity KTX : 1.4.0
AndroidX AppCompat 1.4.0
```

And I m still using below : 

```
Compile SDK Version 30
Target SDK Version 30
Kotlin: 1.5.30
Gradle: 6.7.1
Gradle Plugin: 4.2.2
AndroidX AppCompat 1.3.1
```

**Comment by FitApps7** [comment]
First: you have to use 1.2.11 version for this, and upgrade you SDK level also

**Comment by axitasavani** [comment]
@FitApps7  Okay.

**Comment by akexorcist** [comment]
Since AndroidX AppCompat has per-app language preferences for backward compatibility. Please migrate this library to AndroidX for more stability, compatibility, and longer support from Google team.

See [Migrate to AndroidX guide](https://github.com/akexorcist/Localization/blob/master/MIGRATE_TO_ANDROIDX.md)

Thank you for your support
