### ISSUE TITLE
BlankDummyActivity don't find nim.animation_localization_activity_transition_out

### ISSUE THREAD

**Issue by makhnnar** [akexorcist/Localization#36]
ava.lang.NoClassDefFoundError: Failed resolution of: Lcom/akexorcist/localizationactivity/R$anim;
        at com.akexorcist.localizationactivity.ui.BlankDummyActivity.onCreate(BlankDummyActivity.java:13)
        at android.app.Activity.performCreate(Activity.java:6942)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.akexorcist.localizationactivity.R$anim" on path: DexPathList[[zip file "/data/app/com.my.myapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.my.myapp-2/lib/arm, /data/app/com.my.myapp-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

Before this, my app was working fine, but after some changes on my code, my app began to crash when i'm trying to change App's language

**Comment by makhnnar** [comment]
I solved this issue, editing library's code. I commented BlankDummyActivity invocation in language transaction
