### ISSUE TITLE
ClassCastException on language change

### ISSUE THREAD

**Issue by zhombie** [akexorcist/Localization#89]
Exceptions occurs when language is changed. Sample project was used as example

<img width="935" alt="Screenshot 2021-02-03 at 04 58 07" src="https://user-images.githubusercontent.com/26120169/106678375-69f7f380-65dc-11eb-8222-79ae885b2695.png">

**Comment by akexorcist** [comment]
Hi @zhombie. Sorry for lately response

Could you give more information about testing device? This kind of issue might causing from Xiaomi's MIUI more than my library. Refer to https://stackoverflow.com/questions/64565156/miui-11-12-theme-switch-results-in-lifecycleexception-classcastexception

Besides the example code in the sample project. Is there any more code?

**Comment by zhombie** [comment]
Hi, not a problem, thanks for response.

Device info: Xiaomi Mi Note 9 Pro, MIUI 12.0.1

I already have forceDarkAllowed = false set for >29 sdk style. But it does not help. Yeap, it has other code near, but i don't think that other code can cause such problems

**Comment by akexorcist** [comment]
@zhombie Okay. Let me borrow the Xiaomi device from my colleague 😂

To reproduce this issue, just run the sample project in Xiaomi device. Is this right?

**Comment by zhombie** [comment]
Yeap, i have tried to reproduce the issue with the sample project, it gives me the same exception

**Comment by akexorcist** [comment]
@zhombie As I tested on Redmi Note 9 (MIUI 12.0.6). I got same error log without app crashing and language has changed properly. 

```
E/ActivityInjector: get life cycle exception
    java.lang.ClassCastException: android.os.BinderProxy cannot be cast to android.app.servertransaction.ClientTransaction
        at android.app.ActivityInjector.checkAccessControl(ActivityInjector.java:24)
        at android.app.Activity.onResume(Activity.java:1859)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:455)
        at com.akexorcist.localizationactivity.ui.LocalizationActivity.onResume(LocalizationActivity.kt:28)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
        at android.app.Activity.performResume(Activity.java:8050)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4290)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4332)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:57)
        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5368)
        at android.app.ActivityThread.access$3600(ActivityThread.java:233)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2081)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7561)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

This seem caused by calling `Activity.recreate()` in Xiaomi's firmware. Even I tried calling `Activity.recreate()` without language changing. So I have to say that a firmware issue and we can't fix this.

This is not only happen to my library. A few developers also found this problem from calling `Activity.recreate()` in Xiaomi's device.
* [AppCompatDelegate.setDefaultNightMode doesn't work on physical device](https://stackoverflow.com/questions/65073238/appcompatdelegate-setdefaultnightmode-doesnt-work-on-physical-device)
* [MIUI 11/12 Theme Switch Results in LifeCycleException, ClassCastException](https://stackoverflow.com/questions/64565156/miui-11-12-theme-switch-results-in-lifecycleexception-classcastexception)
* [Getting Lifecycle Exception While Recreating The Activity
](https://stackoverflow.com/questions/63209993/getting-lifecycle-exception-while-recreating-the-activity)

**Comment by zhombie** [comment]
Yeap, it is fairly vendor's problem and everything works fine, just some unexpected things could happen. I opened issue, in order to know if you have solution to this issue

**Comment by akexorcist** [comment]
@zhombie You've done the great things. Even I can't solve this vendor's problem but I've learned about this as known issue. 😆

**Comment by AlexSuvorov2k** [comment]
Same problem on Redmi Note 10 👍
